### ISSUE TITLE
Auto-publish a PHAR executable

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-upgrader#100]
Because we are using `composer global require` as our recommended way of installing the upgrader, some users will run into dependency conflicts:
* #95 
* #27 

Publishing a PHAR executable file will bypass this problem. Our [SSPAK project](https://github.com/silverstripe/sspak) has automated this process.

# Acceptance criteria
* A build script is created that packages the upgrader as a PHAR executable (run manually)
* Installation instructions are updated with alternative installation steps.

# Excludes

* The build script autoruns when new release are created and the resulting file is uploaded to a GH page.

# Pull Request
* [x] #124 
* [x] https://github.com/silverstripe/silverstripe-framework/pull/8248

**Comment by silbinarywolf** [comment]
I've hit these issues as well. My workaround is to simply install the upgrader into the project and run the upgrader from the `vendor` folder.
