### ISSUE TITLE
SS_Log::log() calls aren't upgraded to use new logging methods/classes

### ISSUE THREAD

**Issue by silbinarywolf** [silverstripe/silverstripe-upgrader#113]
**The problem**
`SS_Log::log` calls aren't upgraded.
A lot of modules at Symbiote use this pattern as well as a few projects.

It'd be nice-to-have if the upgrader handled this case.

**Things to consider**
- `SS_Log::log($ex, SS_Log::ERR);` handles passing in an exception object.
- `SS_Log::log($message, SS_Log::ERR);` handles passing in a simple string.

**The solution**
~~I have no idea! I don't have much/any experience doing logging in SS4.~~
Replace with suggested fix here:
https://docs.silverstripe.org/en/4/changelogs/4.0.0/#psr3-logging

**Comment by maxime-rainville** [comment]
We already have an issue open for this https://github.com/silverstripe/silverstripe-framework/issues/7915

**Comment by maxime-rainville** [comment]
@silbinarywolf I'll close this for now. If you feel the other issue doesn't reflect your suggestion correctly, just post here and I'll reopen it.
