### ISSUE TITLE
PHP 5.6 compatiblity

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/silverstripe-upgrader#115]
Would it be possible to make recent versions of this tool work on php 5.6?  

Making it require php 7.1 adds an additional roadblock to uptake on this tool

I've downgraded my own php from 7.1 to 5.6 because if you're dealing with a SilverStripe site less than 3.6, then you can't use php 7.1, and are forced to use php 5.6

For this reason, a lot, if not most, people who want to use this tool will be on php 5.6 because the vast majority of current ss3 sites out in the wild are 3.5 or less

**Comment by maxime-rainville** [comment]
One of the dependency we use `phpstan/phpstan` is only compatible with PHP `7.1`. I don't think we have an easy way to substitute this dependency for something else :crying_cat_face:

You should be able to upgrade your code on a PHP 7 machine and still have the code be PHP 5.6 compatible. What OS are you running on right now?

**Comment by ailionx** [comment]
@maxime-rainville Actually I tried to use php7.1 to upgrade and switch back to  php5.6, then errors happen because the upgrade tool will add dependencies that are compatible with php7.1 but not php5.6. So that's not a perfect solution.

**Comment by kinglozzer** [comment]
Sounds like https://github.com/silverstripe/silverstripe-framework/issues/8474 was the same issue. Could we add an argument for target PHP version which would include the following in `composer.json` as part of the recompose command?

```json
"config": {
    "platform": {
        "php": "5.6"
    }
}
```

**Comment by chillu** [comment]
Sorry, the underlying lib doesn't allow us to do that. PHP 5.x will be unsupported in Dec, so I don't think it's worth putting any energy into this
