### ISSUE TITLE
RFC Using rector in our own upgrader and developing generic PHP upgrade features

### ISSUE THREAD

**Issue by TomasVotruba** [silverstripe/silverstripe-upgrader#128]
Hey everyone, I must admit, I've never heard about Silverstripe before (Is it PHP framework for building CMS?)

I'm pleasently surprised you're working on an upgrade tool for the framework. It looks pretty good - to be honest, the best I saw out there. [CakePHP has similar upgrade tool](https://github.com/cakephp/upgrade), but these tool tend to suffer from being too specific to the one framework.

I think it could be done better, in generic way for any framework. I cooperate with other PHP framework to create such a tool.

It's [called Rector](https://github.com/rectorphp/rector) and I think you might like it, use it or get inspired by it (in any way). Let me know if you'd like to use it partially in any one. 

I'll be working on Rector for a long time, since it's my pet project and I'm not coupled to any specific PHP framework.

Feel free to close this issues and keep up great work, it's great to see these projects pop-up in PHP world :+1: :heart:

**Comment by maxime-rainville** [comment]
Hi @TomasVotruba. Thanks for taking the time to drop by our little corner of GitHub. SilverStripe is both a CMS and a Framework ... basically the [SilverStripe CMS](https://www.silverstripe.org/software/cms/) is built on top of the [SilverStripe Framework](https://www.silverstripe.org/software/framework).

I had a glance rector. It looks pretty cool and seems to be using a lot of the same bag of tricks our upgrader is using. I'll re-purpose your issue has an RFC.

The question is basically this:
**Could/should we use `rector` to implement some of the features the our upgrader currently provides?**

This could mean when we need new features, we implement them in rector instead.

**Comment by TomasVotruba** [comment]
Thanks for nice words!

> ...a lot of the same bag of tricks our upgrader is using

I looked for this project only for a short time, but I like the naming, it's clear and right to the point. Great job!

Btw, I'm strugling with type resolving:

```php
$varirable = new SomeClass;
// $varirable is type of "SomeClass"
```

It works in Rector at the moment, but it's super slow because it analyses all the variables before starting the process. Have you managed to resolve only types that are needed?

> Could/should we use rector to implement some of the features the our upgrader currently provides?

I believe you can!

Do you mean specific configs for silverstripe like [this](https://github.com/rectorphp/rector/blob/master/config/level/cakephp/cakephp36.yml)? If so, what version would be most helpful to you to start with?

**Comment by dhensby** [comment]
Well, I'm always in support of using existing tools to lower our maintenance burden and especially if it means making our tools (or the tools we contribute) more generic and less SilverStripe-centric.

If it's feasible to implement new features in rector then maybe we should give it a go / spike it out?

@TomasVotruba would you be able to look at some of the open issues on this repo and maybe provide guidance on how we could solve one of them using rector?

**Comment by TomasVotruba** [comment]
Hey Dan, thanks for the issue suggestion, I'm on it!


I've check them careful and if I understand that correctly, these are already h
andled by Rector. I always add *how to snippet* so everyone can try it:

- https://github.com/silverstripe/silverstripe-upgrader/issues/50

    ```yaml
    # rector.yml
    services:
        Rector\Rector\Dynamic\ClassReplacerRector:
            $oldToNewClasses:
                OldClass: Namespaced\NewClass
    ```

    than CLI command:

    ```bash
    vendor/bin/rector process /src --config rector.yml
    ```

**Comment by TomasVotruba** [comment]
@dhensby Sorry, I forgot to reply explicitly.

What exactly I can help you with?

Let's start with 1-2 simple tasks, so you'll understand how Rector works.

**Comment by TomasVotruba** [comment]
Outdated, closing
