### ISSUE TITLE
Unable to upgrade CWP projects easily

### ISSUE THREAD

**Issue by micmania1** [silverstripe/silverstripe-upgrader#134]
## Acceptance Criteria

 * I can upgrade a CWP 1.x recipe to 2.x using the upgrader tool
 * The process works with different CWP recipe versions (e.g. 1.4.0 and 1.6.0)
 * I can specify the CWP target recipe version (rather than the core recipe version because that doesn't mean much to CWP developers)
 * Any changes in the upgrade process are documented (on doc.ss.org and/or cwp.govt.nz)
 * Recipes which no longer apply are removed

## Details

The upgrader tool is unable to update composer dependencies of a CWP project as they've been split out. There are two custom modules below which also have problems, however these can be ignored as they're easy to work around and are project-specific.

```
micmania1@micmania1-XPS-15-9560:~/projects/<PROJECT>$ ss-upgrader all --namespace '\App' --psr4


********************************************************************************
*                                                                              *
*  STEP 1 - RUNNING RECOMPOSE                                                  *
*                                                                              *
********************************************************************************

Upgrading PHP constraint
========================

 Done.

Rebuilding dependencies
=======================

 ! [NOTE] Trying to re-require all packages

 * Requiring php:">=5.6" ........................................................................... ✔
 * Requiring silverstripe/recipe-core:"4.2.1" .......................................... ✔
 * Requiring cwp/cwp-recipe-basic ..................... ✗
 * Requiring cwp/cwp-recipe-blog ....... ✗
 * Requiring silverstripe/textextraction ........ ✔
 * Requiring jonom/silverstripe-version-history ........... ✗
 * Requiring nzta/silverstripe-sitebanner ........ ✔
 * Requiring cheddam/silverstripe-flash-messages ...... ✗
 * Requiring heyday/silverstripe-colorpalette ........ ✔
 * Requiring heyday/silverstripe-menumanager ........ ✔
 * Requiring heyday/silverstripe-versioneddataobjects ........ ✔
 * Requiring sheadawson/silverstripe-dependentdropdownfield .......... ✔
 * Requiring sheadawson/silverstripe-linkable ........ ✔
 * Requiring silverstripe/raygun ......... ✔
 * Requiring silverstripe/gridfieldqueuedexport ........... ✔

 ! [NOTE] Trying to curate dependencies by switching to recipes.

 Adding `silverstripe/recipe-core` to substitute:

 * Requiring silverstripe/recipe-core ............ ✔

 !
 ! [CAUTION] Done with warnings.
 !

 * Could not find a compatible version of `jonom/silverstripe-version-history`
 * Could not find a compatible version of `cheddam/silverstripe-flash-messages`
 * Could not find a compatible version of `cwp/cwp-recipe-basic`
 * Could not find a compatible version of `cwp/cwp-recipe-blog`

Showing difference
==================

modified:       /home/micmania1/projects/<PROJECT>/composer.json
@@ -2,24 +2,22 @@
     "name": "cwp/cwp-installer",
     "description": "CWP Project Template",
     "license": "BSD-3-Clause",
-
     "require": {
-
         "jonom/silverstripe-version-history": "dev-bug-fixes",
-        "nzta/silverstripe-sitebanner": "dev-feature/session-banners-can-view",
-
-        "silverstripe/textextraction": "2.1.x-dev#351d71bcdcf533811408cd595d805da8c6abdf16",
-
+        "nzta/silverstripe-sitebanner": "^2.0@dev",
+        "silverstripe/textextraction": "^3.0",
         "cheddam/silverstripe-flash-messages": "^1",
         "cwp/cwp-recipe-basic": "^1",
         "cwp/cwp-recipe-blog": "^1",
-        "heyday/silverstripe-colorpalette": "^1",
-        "heyday/silverstripe-menumanager": "^2",
-        "heyday/silverstripe-versioneddataobjects": "^2",
-        "sheadawson/silverstripe-dependentdropdownfield": "^1",
-        "sheadawson/silverstripe-linkable": "^1",
-        "silverstripe/raygun": "^1",
-        "silverstripe/gridfieldqueuedexport": "^1"
+        "heyday/silverstripe-colorpalette": "^2.0",
+        "heyday/silverstripe-menumanager": "^3.0",
+        "heyday/silverstripe-versioneddataobjects": "^2.0",
+        "sheadawson/silverstripe-dependentdropdownfield": "^2.0",
+        "sheadawson/silverstripe-linkable": "^2.0",
+        "silverstripe/raygun": "^2.1",
+        "silverstripe/gridfieldqueuedexport": "^2.1",
+        "php": ">=5.6",
+        "silverstripe/recipe-core": "^4.2"
     },
     "require-dev": {
         "cwp/cwp-recipe-basic-dev": "^1",
@@ -34,7 +32,7 @@
     "config": {
         "process-timeout": 900
     },
-    "extra": [],
+    "extra": {},
     "repositories": [
         {
             "type": "composer",
@@ -52,4 +50,3 @@
     "prefer-stable": true,
     "minimum-stability": "dev"
 }
-

 ! [NOTE] Changes have been saved.

Trying to install new dependencies
==================================

 Trying to install dependencies ......................................... ✗


  Composer could not resolved your updated dependencies. You'll need to manually resolve conflicts.


all [-d|--root-dir ROOT-DIR] [-S|--strict] [-R|--recipe-core-constraint [RECIPE-CORE-CONSTRAINT]] [-P|--composer-path [COMPOSER-PATH]] [--skip-add-namespace] [-N|--namespace [NAMESPACE]] [--skip-reorganise] [--skip-webroot] [-p|--psr4]
```

I then try to manually update the dependencies following this guide: https://www.cwp.govt.nz/developer-docs/en/2/releases_and_changelogs/cwp_recipe_basic_2.0.0

I then run composer update:

```
micmania1@micmania1-XPS-15-9560:~/projects/<project>$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for cwp/cwp-recipe-core 2.0.0@stable -> satisfiable by cwp/cwp-recipe-core[2.0.0].
    - cwp/cwp-recipe-core 2.0.0 requires silverstripe/recipe-core 1.1.1@stable -> satisfiable by silverstripe/recipe-core[1.1.1] but these conflict with your requirements or minimum-stability.
  Problem 2
    - silverstripe/recipe-cms 1.1.1 requires silverstripe/recipe-core 1.1.1@stable -> satisfiable by silverstripe/recipe-core[1.1.1] but these conflict with your requirements or minimum-stability.
    - silverstripe/recipe-services 1.0.0 requires silverstripe/recipe-cms 1.1.1@stable -> satisfiable by silverstripe/recipe-cms[1.1.1].
    - Installation request for silverstripe/recipe-services 1.0.0@stable -> satisfiable by silverstripe/recipe-services[1.0.0].
```

Then I have to manually try and figure out what's wrong. Fixing one problem leads to another.

As a side note, because the recompose step fails no other step gets executed meaning the project is in a largely unchanged state.

# Sub Tasks
* [x] Figure out recipe equivalences
* [x] Get Recipe equivalence into Rebuild Rule
* [x] Update `Rebuild::switchToRecipeCore()`
* [x] Update `recompose` so it can target `cwp-core`
* [x] Adjust all-in-one command
* [x] Update Unit tests
* [x] Test on real CWP project
* [x] Update Upgrading guide
* [ ] Post release: notify comms so they can update their CWP upgrade guide

# Pull Requests
* [ ] https://github.com/silverstripe/silverstripe-upgrader/issues/145
* [ ] https://github.com/silverstripe/silverstripe-framework/pull/8693

**Comment by NightJar** [comment]
As an extension of this, perhaps it would be good for the upgrader to have knowledge of 'grandfathered' recipes, similar as it does for the likes of classes.
```
 * Requiring cwp/cwp-recipe-basic ..................... ✗
 * Requiring cwp/cwp-recipe-blog ....... ✗
```
These two (the other two being aforementioned custom modules) are both "no longer a thing" with CWP 2, instead being substituted for a collection of `cwp-recipe-cms` and friends, and the latter is now `silverstripe/recipe-blog`.

**Comment by maxime-rainville** [comment]
Starting work on this. Just want to confirm which  CWP 1 recipes/modules need to be substituted with which CWP 2 equivalent. Here's what I've got so far:
* `cwp/cwp-recipe-basic` => `cwp/cwp-recipe-cms`
* `cwp/cwp-recipe-blog` => `cwp/cwp-recipe-cms` + `silverstripe/recipe-blog`
* `cwp/cwp-core` => `cwp/cwp-recipe-core`

What am I missing?

**Comment by maxime-rainville** [comment]
If you are running `silverstripe/cms` in SS3, the upgrader will replace that dependency with `silverstripe/recipe-cms`. The logic here is that `cms` became more modular. So if you want feature parity, what you really want is `recipe-cms`. `framework` and `recipe-core` have a similar relationship.

Is the relationship between `cwp/cwp-core` and `cwp/cwp-recipe-core` similar?

I just had a look at `cwp-recipe-blog`. It doesn't reference any cwp specific module, so `recipe-blog` is indeed a good equivalent.

**Comment by NightJar** [comment]
`cwp-core` is the base configuration, including necessary modules (`hybridsessions` and `auditor`).

`cwp-recipe-core` adds 2 modules (`environmentcheck` and `mimevalidator`) - I'm not sure of their necessity for the base platform product. The only file it adds is a configuration for environmentcheck. And I guess provides a small integration test point for us with collective [phpunit runs over a series of modules together](https://github.com/silverstripe/cwp-recipe-core/blob/master/phpunit.xml.dist).

For the most part it simply adds the 'starting point' files, such as `.htaccess`, etc. - because it's a recipe and that includes magic for copying files around from other recipes rather than just installing modules and exposing assets (at least to my knowledge, could be wrong).

There's literally nothing in it, other than magic.

I thought there was more to it like the other recipes, sorry. Upon review I guess there's no harm in replacing `cwp-core` with `cwp-recipe-core`.

Some things translate, and some don't. In general it's good to be cautious about the difference between recipes and direct inclusion 🤷‍♂️ 

I think there was a good overview of the new recipes when CWP2 was released
The following links may help provide context for you:
https://www.cwp.govt.nz/developer-docs/en/2/releases_and_changelogs/cwp_recipe_basic_2.0.0/
https://www.cwp.govt.nz/developer-docs/en/2/working_with_projects/recipes_and_supported_modules/
https://www.cwp.govt.nz/updates/news/cwp-2-0-release/ (`Recipes & functionality provided` subheading)
