### ISSUE TITLE
Branching needs updating

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-upgrader#142]
The latest release is 1.2.2 but the branch alias on master is 1.1.x-dev, this is misleading for users wanting to run dev versions (without using dev-master)

**Comment by maxime-rainville** [comment]
I don't think we use the same branching logic on the upgrader as with our other modules. We have a 1.0 and 1.1 branch, but there's essentially 0 chance we'll ever do a patch release for 1.0 or 1.1.

I think we're better off telling people to install whatever the latest release is and to install `master` if they want to work with the dev version.

**Comment by chillu** [comment]
Agreed, I've deleted the 1.0 and 1.1 branches
