### ISSUE TITLE
Better version management

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-upgrader#148]
Right now, we track the version of the upgrader manually in https://github.com/silverstripe/silverstripe-upgrader/blob/766df2a10ea3034ce3501f4e7d51a26442695f6c/bin/upgrade-code#L25

This involves incrementing this before each release, which we sometimes forget.

Ideally we could dynamically detect that number:
* by checking the branch if the upgrader is installed globally with compsoer ;
* by setting it a build time when creating the phar.

We could also update the PHAR build process to publish a file containing the latest version number. This would allow us to warn users when a newer version is available.

**Comment by be2n** [comment]
> This would allow us to warn users when a newer version is available.
This benefit ^, in particular, is something that will help to ensure developers have all the assistance the upgrader can offer and they don't miss out on any improvements.

**Comment by chillu** [comment]
Closing in favour of https://app.zenhub.com/workspaces/open-sorcerers-52b2f493f0808b12020000f8/issues/silverstripe/silverstripe-upgrader/130
