### ISSUE TITLE
Upgrader needs to exclude paths with _manifest_exclude file

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-upgrader#15]
As these are thirdparty and not a part of core, they should not be upgraded.

**Comment by tractorcow** [comment]
See https://github.com/open-sausages/silverstripe-framework/commit/f61047d949d654c3e8dc4c1e82adfdd2482ace34 and https://github.com/open-sausages/silverstripe-framework/commit/c9e5f26615fc8558f5b5a4ec74fc42d87c9b7847 as examples of commits that mistakenly upgraded thirdparty dir.

**Comment by dhensby** [comment]
I'm going to assume this is done because of it's age and so many people would have reported problems otherwise
