### ISSUE TITLE
recompose throws an error while updating composer  , exceeded the timeout of 60 seconds.

### ISSUE THREAD

**Issue by utmsandeep** [silverstripe/silverstripe-upgrader#154]
C:\wamp64\www>php upgrade-code.phar recompose --write

Upgrading PHP constraint
========================

 Done.

Rebuilding dependencies
=======================

 ! [NOTE] Trying to re-require all packages

 * Requiring php:">=5.6" ......... ✔
 * Requiring silverstripe/recipe-core:"4.3.0" ....................................................................................... ✔
 * Requiring silverstripe/recipe-cms:"*" .................................................................................................................................... ✔
 * Requiring silverstripe/reports:"*" ............................................................................................................................................... ✔
 * Requiring silverstripe/siteconfig:"*" ............................................................................................................................. ✔
 * Requiring silverstripe-themes/simple:"*" .............................................................................................................................. ✔

In Process.php line 1236:

  The process "composer update --working-dir="C:\Users\PKGUPT~1\AppData\Local\Temp\ss-upgrader-5c53e7ac309a8" --prefe
  r-stable --ignore-platform-reqs --no-plugins" exceeded the timeout of 60 seconds.

recompose [-d|--root-dir ROOT-DIR] [-w|--write] [-S|--strict] [-R|--recipe-core-constraint [RECIPE-CORE-CONSTRAINT]] [--cwp-constraint [CWP-CONSTRAINT]] [-P|--composer-path [COMPOSER-PATH]] [-Q|--quick]

# Pull request
* [x] https://github.com/silverstripe/silverstripe-upgrader/pull/173

**Comment by maxime-rainville** [comment]
The `recompose` command calls composer to perform a various operations. My guess is you are running against composer's [`process-timeout`](https://getcomposer.org/doc/06-config.md#process-timeout).

60 seconds is a bit short for this however. The default value should be 300 seconds. Try running this command to confirm what your current limit is `composer config process-timeout`. If it comes back with 60 seconds try increasing it to 300 or 600 seconds with `composer config process-timeout 300`.

**Comment by maxime-rainville** [comment]
@utmsandeep Any luck?

**Comment by dnsl48** [comment]
Please feel free to reopen if you still have the issue happening.

**Comment by maxime-rainville** [comment]
Figured out what the issue is. The composer command runs inside a Symfony Process. Composer's timeout is 300 sec, but the Symfony Process also has a timeout which is 60 sec.

I've increase the Process timeout to match the default composer timeout. https://github.com/silverstripe/silverstripe-upgrader/pull/173
