### ISSUE TITLE
Upgrader needs to support ability to ignore specific strings.

### ISSUE THREAD

**Issue by tractorcow** [silverstripe/silverstripe-upgrader#16]
E.g. with this config

``` yaml
ignore_strings:
  - 'Form'
```

Any literal 'Form' string will not be upgraded, as in some cases these strings are more often than not a form action name, not a form class. In this case we can mark these for manual upgrade.

# Related PRs
* [x] https://github.com/silverstripe/silverstripe-framework/pull/8768

**Comment by dhensby** [comment]
*needs* is a strong word for a feature that's been almost 2 years and not done ;)

**Comment by maxime-rainville** [comment]
@dre has at least partially address this issue while fixing #149. We probably should add Form to the list of ambiguous class substitution.

**Comment by maxime-rainville** [comment]
PR got merged.
