### ISSUE TITLE
Add a new command to auto-generate database table names

### ISSUE THREAD

**Issue by madmatt** [silverstripe/silverstripe-upgrader#162]
This could either be a new command, or added on to the `upgrade` command. For any class that is a descendent of `DataObject`, automatically add `private static $table_name = '<short class name>';` to the top of the class definition.

Seems straightforward enough, and would save a decent chunk of time having to open every PHP file in a project and make a trivial change.

**Comment by phptek** [comment]
+100 for this. I spoke to @robbieaverill a few days ago about this on Slack. I still don't understand why a default for `$table_name` in framewokr itself, wasn't implemented as just using the current class' short name - ostensibly zero difference for devlopers and the database itself when upgrading from 2/3 to 4.

**Comment by sunnysideup** [comment]
I reckon by default the table name should be the short class name with the ability of using table_name to override it....

**Comment by maxime-rainville** [comment]
Duplicate of https://github.com/silverstripe/silverstripe-upgrader/issues/162
