### ISSUE TITLE
add-namespace --psr4 double backslash

### ISSUE THREAD

**Issue by christopherdarling** [silverstripe/silverstripe-upgrader#170]
When running upgrade-code add-namespace "App\\Web" ./mysite/code --recursive --write --psr4

it results in `namespace App\Web\\Models;` in my php files. I presume this is down to https://github.com/silverstripe/silverstripe-upgrader/blob/master/src/UpgradeRule/PHP/AddNamespaceRule.php#L66

Same issue happens in the .upgrade.yml file generated by this command

# Pull requests
* [ ] https://github.com/silverstripe/silverstripe-upgrader/pull/171

**Comment by maxime-rainville** [comment]
It's probably just a question of removing any trailing backslashes.

**Comment by maxime-rainville** [comment]
Here's a quick fix https://github.com/silverstripe/silverstripe-upgrader/pull/171

**Comment by kinglozzer** [comment]
Closed by https://github.com/silverstripe/silverstripe-upgrader/pull/171
