### ISSUE TITLE
upgrade fails on classes that are not a subclass of SilverStripe

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/silverstripe-upgrader#178]
> Fatal error: Uncaught TypeError: Argument 1 passed to SilverStripe\Upgrader\UpgradeRule\PHP\Visitor\ClassToTraitVisitor::getNodeName() must implement interface PhpParser\Node, null given, called in ...\vendor\silverstripe\upgrader\src\UpgradeRule\PHP\Visitor\ClassToTraitVisitor.php on line 48 and defined in ...\vendor\silverstripe\upgrader\src\
UpgradeRule\PHP\Visitor\NodeMatchable.php:42

The class is  a simple PHP class with nothing fancy, like:

```
<?php

namespace Foo\View;

class MyClass
{
    public $ID;
}
```

making it a subclass of e.g. ArrayData removes that error

# Pull requests
* [x] https://github.com/silverstripe/silverstripe-upgrader/pull/180

**Comment by maxime-rainville** [comment]
https://github.com/silverstripe/silverstripe-upgrader/pull/180 should fix this issue.

**Comment by ScopeyNZ** [comment]
#180 is merged and released!
