### ISSUE TITLE
CAN'T INSTALL: requires symfony/requirement can not be met. Help¡¡

### ISSUE THREAD

**Issue by brayatzuya** [silverstripe/silverstripe-upgrader#190]
Changed current directory to C:/Users/STALKER/AppData/Roaming/Composer
Using version ^3.0 for laravel/installer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
 Problem 1
    - Conclusion: don't install laravel/installer v3.0.1
    - Conclusion: remove symfony/console v3.4.39
    - Installation request for laravel/installer ^3.0 -> satisfiable by laravel/installer[v3.0.0, v3.0.1].
    - Conclusion: don't install symfony/console v3.4.39
    - laravel/installer v3.0.0 requires symfony/console ^4.0|^5.0 -> satisfiable by symfony/console[v4.0.0, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.15, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.1, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v5.0.0, v5.0.1, v5.0.2, v5.0.3, v5.0.4, v5.0.5, v5.0.6, v5.0.7].
    - Can only install one of: symfony/console[v4.0.0, v3.4.39].
    - Can only install one of: symfony/console[v4.0.1, v3.4.39].
    - Can only install one of: symfony/console[v4.0.10, v3.4.39].
    - Can only install one of: symfony/console[v4.0.11, v3.4.39].
    - Can only install one of: symfony/console[v4.0.12, v3.4.39].
    - Can only install one of: symfony/console[v4.0.13, v3.4.39].
    - Can only install one of: symfony/console[v4.0.14, v3.4.39].
    - Can only install one of: symfony/console[v4.0.15, v3.4.39].
    - Can only install one of: symfony/console[v4.0.2, v3.4.39].
    - Can only install one of: symfony/console[v4.0.3, v3.4.39].
    - Can only install one of: symfony/console[v4.0.4, v3.4.39].
    - Can only install one of: symfony/console[v4.0.5, v3.4.39].
    - Can only install one of: symfony/console[v4.0.6, v3.4.39].
    - Can only install one of: symfony/console[v4.0.7, v3.4.39].
    - Can only install one of: symfony/console[v4.0.8, v3.4.39].
    - Can only install one of: symfony/console[v4.0.9, v3.4.39].
    - Can only install one of: symfony/console[v4.1.0, v3.4.39].
    - Can only install one of: symfony/console[v4.1.1, v3.4.39].
    - Can only install one of: symfony/console[v4.1.10, v3.4.39].
    - Can only install one of: symfony/console[v4.1.11, v3.4.39].
    - Can only install one of: symfony/console[v4.1.12, v3.4.39].
    - Can only install one of: symfony/console[v4.1.2, v3.4.39].
    - Can only install one of: symfony/console[v4.1.3, v3.4.39].
    - Can only install one of: symfony/console[v4.1.4, v3.4.39].
    - Can only install one of: symfony/console[v4.1.5, v3.4.39].
    - Can only install one of: symfony/console[v4.1.6, v3.4.39].
    - Can only install one of: symfony/console[v4.1.7, v3.4.39].
    - Can only install one of: symfony/console[v4.1.8, v3.4.39].
    - Can only install one of: symfony/console[v4.1.9, v3.4.39].
    - Can only install one of: symfony/console[v4.2.0, v3.4.39].
    - Can only install one of: symfony/console[v4.2.1, v3.4.39].
    - Can only install one of: symfony/console[v4.2.10, v3.4.39].
    - Can only install one of: symfony/console[v4.2.11, v3.4.39].
    - Can only install one of: symfony/console[v4.2.12, v3.4.39].
    - Can only install one of: symfony/console[v4.2.2, v3.4.39].
    - Can only install one of: symfony/console[v4.2.3, v3.4.39].
    - Can only install one of: symfony/console[v4.2.4, v3.4.39].
    - Can only install one of: symfony/console[v4.2.5, v3.4.39].
    - Can only install one of: symfony/console[v4.2.6, v3.4.39].
    - Can only install one of: symfony/console[v4.2.7, v3.4.39].
    - Can only install one of: symfony/console[v4.2.8, v3.4.39].
    - Can only install one of: symfony/console[v4.2.9, v3.4.39].
    - Can only install one of: symfony/console[v4.3.0, v3.4.39].
    - Can only install one of: symfony/console[v4.3.1, v3.4.39].
    - Can only install one of: symfony/console[v4.3.10, v3.4.39].
    - Can only install one of: symfony/console[v4.3.11, v3.4.39].
    - Can only install one of: symfony/console[v4.3.2, v3.4.39].
    - Can only install one of: symfony/console[v4.3.3, v3.4.39].
    - Can only install one of: symfony/console[v4.3.4, v3.4.39].
    - Can only install one of: symfony/console[v4.3.5, v3.4.39].
    - Can only install one of: symfony/console[v4.3.6, v3.4.39].
    - Can only install one of: symfony/console[v4.3.7, v3.4.39].
    - Can only install one of: symfony/console[v4.3.8, v3.4.39].
    - Can only install one of: symfony/console[v4.3.9, v3.4.39].
    - Can only install one of: symfony/console[v4.4.0, v3.4.39].
    - Can only install one of: symfony/console[v4.4.1, v3.4.39].
    - Can only install one of: symfony/console[v4.4.2, v3.4.39].
    - Can only install one of: symfony/console[v4.4.3, v3.4.39].
    - Can only install one of: symfony/console[v4.4.4, v3.4.39].
    - Can only install one of: symfony/console[v4.4.5, v3.4.39].
    - Can only install one of: symfony/console[v4.4.6, v3.4.39].
    - Can only install one of: symfony/console[v4.4.7, v3.4.39].
    - Can only install one of: symfony/console[v5.0.0, v3.4.39].
    - Can only install one of: symfony/console[v5.0.1, v3.4.39].
    - Can only install one of: symfony/console[v5.0.2, v3.4.39].
    - Can only install one of: symfony/console[v5.0.3, v3.4.39].
    - Can only install one of: symfony/console[v5.0.4, v3.4.39].
    - Can only install one of: symfony/console[v5.0.5, v3.4.39].
    - Can only install one of: symfony/console[v5.0.6, v3.4.39].
    - Can only install one of: symfony/console[v5.0.7, v3.4.39].
    - Installation request for symfony/console (locked at v3.4.39) -> satisfiable by symfony/console[v3.4.39].

Installation failed, reverting ./composer.json to its original content.

**Comment by dhensby** [comment]
What command are you running to produce that error?
