### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by OldStarchy** [silverstripe/silverstripe-upgrader#197]
The current composer.json lists

https://github.com/silverstripe/silverstripe-upgrader/blob/c5f0fa4e94439d542cb5c3b6110d5a76145aa9ab/composer.json#L12

Is PHP8 support planned?

**Comment by emteknetnz** [comment]
It's not planned, we've just updated the readme on this module to clarify support of this module going forward:

"The Silverstripe CMS Upgrader has mostly served its purpose. The core Silverstripe CMS team is not actively looking at doing more work on it in the near future. If a community member would like become a maintainer, then we're happy to grant them merge access after some basic due diligence. Please raise an issue to let us know if you would like to maintain this repo."
