### ISSUE TITLE
Class-renames should be able to update yaml

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-upgrader#2]
Although it's probably best handled as a separate upgrade rules, class-renames should be able to be applied to dataobject config:
- `Injector.*.class` values
- Root keys
- ~`%$` references to the old classname should be left as-is, but should scaffold a new injection service pointing to the new class.~ decided to forgo this

**Comment by sminnee** [comment]
This is a duplicate of https://github.com/silverstripe/silverstripe-framework/issues/5635 so I'll leave that one.

**Comment by tractorcow** [comment]
See https://github.com/silverstripe/silverstripe-framework/issues/5635 for story-pointed card.

**Comment by tractorcow** [comment]
PR at https://github.com/silverstripe/silverstripe-upgrader/pull/25
