### ISSUE TITLE
Cannot install with composer on latest master

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-upgrader#24]
The latest versions of `4.x-dev` for core packages introduce nikic/php-parser ^3, which conflicts when trying to install this package:

```
$ composer require --dev silverstripe/upgrader
Using version ^0.0.2 for silverstripe/upgrader
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for silverstripe/upgrader ^0.0.2 -> satisfiable by silverstripe/upgrader[0.0.2].
    - Conclusion: remove nikic/php-parser v3.0.5
    - Conclusion: don't install nikic/php-parser v3.0.5
    - silverstripe/upgrader 0.0.2 requires nikic/php-parser ^2.1 -> satisfiable by nikic/php-parser[2.x-dev, v2.1.0, v2.1.1].
    - Can only install one of: nikic/php-parser[2.x-dev, v3.0.5].
    - Can only install one of: nikic/php-parser[v2.1.0, v3.0.5].
    - Can only install one of: nikic/php-parser[v2.1.1, v3.0.5].
    - Installation request for nikic/php-parser (locked at v3.0.5) -> satisfiable by nikic/php-parser[v3.0.5].


Installation failed, reverting ./composer.json to its original content.
```

Manually running `composer require nikic/php-parser ^2.1` then requiring this package again works.

Note: This project has been slowly upgraded, it's not a fresh install.

**Comment by tractorcow** [comment]
I think it just needs a new tag.

**Comment by robbieaverill** [comment]
Re-testing...

**Comment by robbieaverill** [comment]
@tractorcow suggests installing it globally rather than as a project dependency.

Locally I can't do this as I have other global packages that use symfony/console 3.2, while this package uses 2.3. Constraints could be loosened to support both - logged as #27.

You can install this as a project dependency by requiring a version of php-parser that both SilverStripe and the upgrader can accept together, but not via an OOB install:

```
omposer create-project silverstripe/installer ./ss40upgradertest 4.0.x-dev
cd ss40upgradertest
composer require --dev silverstripe/upgrader
```

**Comment by robbieaverill** [comment]
Re-tested, not a problem any more (with the test above)
