### ISSUE TITLE
Loosen symfony/console constraints

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-upgrader#27]
If the package is installed globally with composer it may conflict with existing global packages.

The latest version of symfony/console at the moment is 3.2, so we could loosen the constraint to `^2.1 | ^3.0` assuming that this utility works on 3.x as well as 2.x.

Resolving this issue would also resolve #24

**Comment by maxime-rainville** [comment]
I like this one. I actually tried running this on Symfony 4.0 and it works just fine. It wouldn't take very long to update our .travis and check if this thing is compatible with 2, 3 and 4.

Alternatively, we could distribute a PHAR file as well.

**Comment by robbieaverill** [comment]
Yeah they aren’t too extreme with api changes between major versions

**Comment by maxime-rainville** [comment]
Fixed as part of #95.
