### ISSUE TITLE
Remove JS upgrades

### ISSUE THREAD

**Issue by unclecheese** [silverstripe/silverstripe-upgrader#28]
We're not going to namespace the JS files as many JS files have no PHP namespace counterpart, and collisions are exceedingly unlikely.

**Comment by sminnee** [comment]
@unclecheese i see you've assigned this to Damian; did you consider wading into it yourself? ;-)

**Comment by unclecheese** [comment]
@tractorcow asked me to do so per our conversation on Slack. I'm not opposed to looking into it, though.

**Comment by sminnee** [comment]
Cool — I'll leave it to you two. It'd be good to get more brains familiar with this codebase, though ;-)

**Comment by unclecheese** [comment]
Addressed in https://github.com/silverstripe/silverstripe-upgrader/pull/30

**Comment by sminnee** [comment]
Merged
