### ISSUE TITLE
nikic/php-parser version

### ISSUE THREAD

**Issue by thezenmonkey** [silverstripe/silverstripe-upgrader#32]
can't install in a fresh SS4-alpha7 because it installs nikic/php-parser v3.0.5, this module requires ^2.5.

**Comment by wernerkrauss** [comment]
Note: you can install it in any direcory (e.g. one dir above) without current composer requirements and are ready to go. Solved it in my VM this way where i wasn't able to install it globally due to this issue.

**Comment by oddnoc** [comment]
FWIW, the solution is to do as the readme says: `composer global require silverstripe/upgrader`

**Comment by tractorcow** [comment]
Yes that's right. Let me know if you have any issues with this. ;)
