### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/silverstripe-upgrader#34]
I get this error:

>   [InvalidArgumentException]
>   basePath must start with /

in src\CodeCollection\DiskItem.php:32

Commenting out this check it works in my git-bash on windows.

**Comment by wernerkrauss** [comment]
Renaming classes runs but doesn't change anything

**Comment by wernerkrauss** [comment]
Updating yml file also works only on linux (got it installed in my VM now), not in windows for some reason.

**Comment by tractorcow** [comment]
Fixed with #42

**Comment by tractorcow** [comment]
@wernerkrauss probably need to do a lot of replacing of `/` with DIRECTORY_SEPARATOR, I would guess.
