### ISSUE TITLE
symfony/yaml conflict

### ISSUE THREAD

**Issue by WillGibson** [silverstripe/silverstripe-upgrader#37]
I cannot install this at the same time as silverstripe/silverstripe-framework 4.0.0-beta1 because this wants symfony/yaml ~2.3 and silverstripe/silverstripe-framework 4.0.0-beta1 wants symfony/yaml ~3.2.

Can this be resolved?

**Comment by tractorcow** [comment]
Fix at https://github.com/silverstripe/silverstripe-upgrader/pull/38
