### ISSUE TITLE
Type inferencing

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-upgrader#40]
A lot of upgrade sniffs will be about particular methods being called on particular classes. To support this, a useful support class in the php-parser would be a type inferencing system, that would augment the AST with type hints before passing on to other more specific checks.

A few thoughts on implementation:

 * The general way that you can do this is do iterative run a pass over things that bubbles type information one step forward, and stops when a single pass is a no-op
 * As well as PHP-generic type information being passed, it would be useful to be able to pass in framework-specific knowledge, for example about Injector::inst()->get().
 * It should read docblock type information
 * The AST may not have space to include this meta-data; it's an open question as to how this data is stored.

This could possibly be a micropackage separate from silverstripe-upgrader, as it may be of use to other users of php-parser.

**Comment by SilbinaryWolf** [comment]
PHPStan does a lot of what you're saying. I've even extended it previously to resolve types for SS-specific things.

Perhaps there's something that can be pulled out from that project?

https://github.com/phpstan/phpstan
