### ISSUE TITLE
DOCS global composer path for Windows

### ISSUE THREAD

**Issue by christopherdarling** [silverstripe/silverstripe-upgrader#47]
`~/.composer/vendor/bin` doesn't work on Windows, the path for Windows users should be `C:\Users\<COMPUTER NAME>\AppData\Roaming\Composer\vendor\bin`

Laravel words this as
``
Make sure to place the $HOME/.composer/vendor/bin directory (or the equivalent directory for your OS) in your $PATH so the laravel executable can be located by your system.
``

**Comment by dhensby** [comment]
Happy for a PR to update the docs :)
