### ISSUE TITLE
Upgrader doesn't work on Windows

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-upgrader#52]
From Dylan:

```
$ upgrade-code upgrade -d /c/Users/dwagstaff/work/repos/silverstripe-html5/
Running upgrades on "C:\Users\dwagstaff\work\repos\silverstripe-html5"


  [InvalidArgumentException]
  basePath must start with /
```

**Comment by tractorcow** [comment]
isWindows() should be returning false for this to occur... @nightjar what are you running this on for this to occur?

**Comment by NightJar** [comment]
And there in lies the trap @tractorcow 
```
$ php -r 'var_dump(strtoupper(substr(PHP_OS,0,3))==="WIN");'
Command line code:1:
bool(true)
```

**Comment by tractorcow** [comment]
The above exception isn't being checked if isWindows() is true though. Can you debug and find out what's going on?

https://github.com/silverstripe/silverstripe-upgrader/blob/66cd880f3a061771d634b481a9e36732cfd3a288/src/CodeCollection/DiskItem.php#L30


https://github.com/silverstripe/silverstripe-upgrader/blob/66cd880f3a061771d634b481a9e36732cfd3a288/src/CodeCollection/DiskItem.php#L105

**Comment by tractorcow** [comment]
I think this was fixed with https://github.com/silverstripe/silverstripe-upgrader/commit/52515a5c23b91e4e9f567f26c6c4fb8a866d7750

@NightJar please update; I've re-tagged 1.0.0, and this should fix your issue.

**Comment by tractorcow** [comment]
@NightJar says it didn't fix it for some reason...

**Comment by NightJar** [comment]
Or maybe my composer is a bit special :/
I installed this yesterday using the command from the docs (`composer global require silverstripe/upgrader`) and it has chosen `^0.0.5` for whatever reason.
I'm going to try re-installing to see if the issue persists now that you've tagged `1.0.0`

**Comment by NightJar** [comment]
Right duh, because of the caret.
changing the global `composer.json` to list `"silverstripe/upgrader": "^1"` has actually seen things update.

**Comment by NightJar** [comment]
This will be a caveat for anyone who already has the upgrader installed on Windows though. They'll have to specify 1.0 when updating.
