### ISSUE TITLE
Running `upgrade` should work with `silverstripe-vendormodule` applied code.

### ISSUE THREAD

**Issue by NightJar** [silverstripe/silverstripe-upgrader#54]
Currently the tool doesn't really work too well when trying to upgrade a module (see #53 ), but once working around this issue the `upgrade` command does not work as expected.

Running `upgrade-code upgrade` (after adding namespaces) in various directories results in:
Webroot:
```
$ upgrade-code upgrade
Running upgrades on "C:\Users\testing\work\testymctestface"
[2017-11-22 15:11:48] Applying RenameClasses to IFramePage.php...
[2017-11-22 15:11:49] Applying RenameClasses to IFramePageController.php...
[2017-11-22 15:11:49] Applying RenameClasses to IFramePageTest.php...
[2017-11-22 15:11:49] Applying RenameClasses to _config.php...
[2017-11-22 15:11:49] Applying RenameClasses to index.php...
[2017-11-22 15:11:49] Applying RenameClasses to install.php...
[2017-11-22 15:11:49] Applying RenameClasses to Page.php...
[2017-11-22 15:11:49] Applying RenameClasses to PageController.php...
[2017-11-22 15:11:49] Applying RenameClasses to _config.php...
[2017-11-22 15:11:49] Applying RenameClasses to config.php...
[2017-11-22 15:11:49] Applying RenameClasses to server.php...
[2017-11-22 15:11:49] Applying RenameClasses to class.tree.php...
[2017-11-22 15:11:49] Applying RenameClasses to class._database.php...
[2017-11-22 15:11:49] Applying RenameClasses to class._database_i.php...
[2017-11-22 15:11:50] Applying RenameClasses to tiny_mce_gzip.php...
Changes not saved; Run with --write to commit to disk
```
Webroot, with specifying a path:
- vendor
- vendor/silverstripe
- vendor/silverstripe/externallinks
- vendor/silverstripe/externallinks/src

All return the same result, e.g.
```
Running upgrades on "C:\Users\testing\work\testymctestface\vendor\silverstripe\externallinks\src"
Changes not saved; Run with --write to commit to disk
```
Running the command from within each of those folders, with varying paths all also return the same result, or:
```
  [InvalidArgumentException]
  No .upgrade.yml definitions found in modules on "C:\Users\testing\work\te
  stymctestface\vendor\externallinks". Please ensure you upgrade your SilverStripe dependen
  cies before running this task.
```
despite:
```
$ pwd && ls .u*
/c/Users/testing/work/testymctestface/vendor/silverstripe/externallinks
.upgrade.yml
```

**Comment by tractorcow** [comment]
@NightJar which version of upgrader are you using?

**Comment by NightJar** [comment]
`1.0.0`

**Comment by tractorcow** [comment]
@NightJar Are you sure there are any classes that need to be upgraded? It's possible that it's a true no-op rather than a false one?

If you like I can check out your project /module and test it myself.

**Comment by NightJar** [comment]
Yes, the entire module is un-namespaced :)
I got around this by:
```
cp -r vendor/silverstripe/externallinks .
upgrade-code upgrade externallinks/src
upgrade-code upgrade externallinks/tests
cp externallinks
git commit -am "yolo"
```
Except the very last statement may be slightly embellished.

**Comment by NightJar** [comment]
@tractorcow you can test by checking out the results of the `add-namespace` command at https://github.com/creative-commoners/silverstripe-externallinks/commit/e6ddf0fe4788d038395702c7404fd6d5549d88eb

**Comment by robbieaverill** [comment]
I'll vouch for this too - I've been moving the folder back to the project root again while I run the upgrader commands, then moving it back into vendor

**Comment by NightJar** [comment]
mmm. The work around is currently:
- Fork & adjust project's composer.json apropriately
- Either update composer.json in place and commit to get it to install (ie. things don't require SS 3), _or_ straight up `git clone` in web root
- use `add-namespace` from the web root
- use `upgrade` from the web root
- change module's composer.json to be `silverstripe-vendormodule` and include the PSR autoloady stuff, etc.
- push to fork branch
- `rm -rf <module>` from web root
- composer update
- _then_ continue upgrading (testing what's already done).

**To be more clear:**
using `add-namespace` _must_ currently happen from the direct parent of the module folder. If it's already vendorised, then that's e.g. `vendor/silverstripe`, otherwise the web root. If this isn't strictly adhered to, then the `.upgrade.yml` gets plonked in the wrong place.

using `upgrade` from the wrong place means that it doesn't work too well (see issue description).

**Comment by tractorcow** [comment]
If we fix #53 then will this issue be fixed also? It's addressed in https://github.com/silverstripe/silverstripe-upgrader/pull/57

**Comment by tractorcow** [comment]
@NightJar I've changed the upgrade tool; You now MUST specify a path that is a subdirectory of the webroot (where this tool must be run). You can't run `upgrade-code upgrade .` anymore.

**Comment by purplespider** [comment]
Sorry, bit confused, so what is the correct way to upgrade a module now?

**Comment by tractorcow** [comment]
Provide the path to the module `upgrade-code upgrade vendor/myvendor/mymodule/code`

**Comment by sminnee** [comment]
FYI `upgrade-code upgrade vendor/myvendor/mymodule/code` doesn't work and I've raised this in #75
