### ISSUE TITLE
Catchable error when running upgrade-code inspect

### ISSUE THREAD

**Issue by wildflower** [silverstripe/silverstripe-upgrader#56]
@upgrade-code inspect ./mysite 
Running inspections on "/home/haydn/Documents/ppsr/mysite"

PHP Catchable fatal error:  Object of class PhpParser\Node\Scalar\String_ could not be converted to string in /home/haydn/.composer/vendor/silverstripe/upgrader/src/UpgradeRule/PHP/Visitor/PropertyWarningsVisitor.php on line 122

# Notes

 * Track under ORB-162
 
# PRs:

 - [ ] https://github.com/silverstripe/silverstripe-upgrader/pull/62

**Comment by tractorcow** [comment]
Can you please provide the actual code being parsed? We can see the source at that point.

**Comment by tractorcow** [comment]
I guess it's something like 

```php
$this->"{$prop}name";
```

 right?

**Comment by tractorcow** [comment]
Nope I can't reproduce a valid php syntax like that. I'll wait for your example. :)

**Comment by PortableSteve** [comment]
I'm getting a similar issue:

```
upgrade-code inspect . -vvv
...
PHP Catchable fatal error:  Object of class PhpParser\Node\Expr\BinaryOp\Concat could not be converted to string in /home/steve/.config/composer/vendor/silverstripe/upgrader/src/UpgradeRule/PHP/Visitor/PropertyWarningsVisitor.php on line 122
```

It seems that it's failing on this line of code:
`return str_ireplace(array('<p>', '</p>'), '', $this->{'CTA'.$label.'Label'});`

**Comment by tractorcow** [comment]
Ah yes, that would do it. ;) Thanks for the feedback. I think we can fix this.
