### ISSUE TITLE
The "--recursive" option does not exist.

### ISSUE THREAD

**Issue by wernerkrauss** [silverstripe/silverstripe-upgrader#58]
When I try (according to the [README](https://github.com/silverstripe/silverstripe-upgrader#upgrading-code))

> upgrade-code upgrade my-module/ --write --recursive

I get

>   [Symfony\Component\Console\Exception\RuntimeException]
  The "--recursive" option does not exist.

**Comment by tractorcow** [comment]
Oh sorry. That's ment to be for add-namespace only. Will fix docs. :)
