### ISSUE TITLE
Offer to rename mysite/ to app/

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-upgrader#60]
# Overview

We're establishing new naming conventions that get away from the weird "mysite" naming, see https://github.com/silverstripe/silverstripe-framework/issues/7946. The 4.x upgrade is a great way to get people on board with that in an automated fashion.

# Acceptance Criteria

 * Rewrites any `mysite/` files into `app/` and related folders (depending on RFC outcome)
 * Rewrites any `mysite/code` files into `app/src`
 * Warns about hardcoded use of "mysite" paths in console output (but doesn't auto-search)
 * Allows opt-out by asking for approval

# Related PR
* [x] #64 
* [x] https://github.com/silverstripe/silverstripe-framework/pull/8021

**Comment by maxime-rainville** [comment]
Waiting on #63 and https://github.com/silverstripe/silverstripe-framework/pull/8011 to be merged.

**Comment by tractorcow** [comment]
Both are merged @maxime-rainville :)
