### ISSUE TITLE
Rewrite to public folder (opt-in)

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-upgrader#65]
# Overview

We want users to adopt the public folder approach to make SilverStripe projects consistent, and more secure by default.

# Acceptance Criteria

 * As a developer upgrading from 3.x or 4.0 to >=4.1, I can opt in to rewriting my project code to use the public folder
 * When choosing this option, I am clear about the implications: The public folder is hardcoded and might not be supported by all hosting environments. I'll need to change my hosting configuration for this to work
 * Checks that `index.php` file is recent (correct `vendor` path)
 * Moves `.htaccess`, `index.php`, `assets`, `resources` into `public`
 * Rewrites the `RewriteRule` part of `.htaccess` (to retain any other customisations)
 * Offers to remove extraneous default rules from `.htaccess`

**Comment by tractorcow** [comment]
Probably should be built into the "reorganise" command.

See https://github.com/silverstripe/silverstripe-upgrader/pull/64

**Comment by chillu** [comment]
Duplicate of https://github.com/silverstripe/silverstripe-framework/issues/7920
