### ISSUE TITLE
can't install dev-master

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-upgrader#69]
Problem 1
    - silverstripe/upgrader dev-master requires phpstan/phpstan ^0.10 -> satisfiable by phpstan/phpstan[0.10.x-dev].
    - Installation request for silverstripe/upgrader dev-master -> satisfiable by silverstripe/upgrader[dev-master].
    - Conclusion: remove nikic/php-parser v2.1.1
    - Conclusion: don't install nikic/php-parser v2.1.1
    - phpstan/phpstan 0.10.x-dev requires nikic/php-parser ^3.1 -> satisfiable by nikic/php-parser[3.x-dev, v3.1.0, v3.1.1, v3.1.2, v3.1.3, v3.1.4, v3.1.5].
    - Can only install one of: nikic/php-parser[3.x-dev, v2.1.1].
    - Can only install one of: nikic/php-parser[v3.1.0, v2.1.1].
    - Can only install one of: nikic/php-parser[v3.1.1, v2.1.1].
    - Can only install one of: nikic/php-parser[v3.1.2, v2.1.1].
    - Can only install one of: nikic/php-parser[v3.1.3, v2.1.1].
    - Can only install one of: nikic/php-parser[v3.1.4, v2.1.1].
    - Can only install one of: nikic/php-parser[v3.1.5, v2.1.1].
    - Installation request for nikic/php-parser (locked at v2.1.1) -> satisfiable by nikic/php-parser[v2.1.1].

**Comment by robbieaverill** [comment]
This issue presents itself occasionally when upgrading from older SilverStripe projects. You can normally install a newer version of nikic/php-parser to workaround it, e.g.:

```
composer require nikic/php-parser ^
```

... then retry your upgrader install command.

**Comment by sunnysideup** [comment]
thank you.
