### ISSUE TITLE
Doesn't handle other classes in same namespace properly

### ISSUE THREAD

**Issue by hafriedlander** [silverstripe/silverstripe-upgrader#7]
If you just run `add-namespace`, depending on order it doesn't know about the other classes that are also being moved into same namespace. So for instance, even though DB and DataObject are both being moved into SilverStripe\ORM, in DataObject there is a `use DB;` statement introduced.

If you then run `upgrade`, it will remove the `use DB;` statement and add a `use SilverStripe\ORM\DB;` instead. While this is "right" (in that it won't break anything), it's "wrong" in that it's redundant. Also, ugly empty lines are left from where the (un-needed) `use DB;` statement was removed.

**Comment by tractorcow** [comment]
The problem is that, when namespacing a file, it "knows" about all classes that exist in that file, to protect against them having aliases assigned.

The fix should be to have these classes discovered on all files to be namespaced up front (per dir) rather than per file.
