### ISSUE TITLE
inspect and upgrade don't work on vendormodules

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-upgrader#75]
Address alongside [Add module upgrade mode](https://github.com/silverstripe/silverstripe-upgrader/issues/85)

This works:

```upgrade-code upgrade elastica```

This doesn't:

```upgrade-code upgrade vendor/symbiote-libary/silverstripe-elastica```

**Comment by sminnee** [comment]
Marking as medium because there is a workaround

**Comment by robbieaverill** [comment]
FYI this was previously reported and closed in https://github.com/silverstripe/silverstripe-upgrader/issues/54

**Comment by sminnee** [comment]
It looks like this is a separate issue.

If it turns out that `upgrade-code upgrade vendor/symbiote-libary/silverstripe-elastica/src` is necessary to run, that's very fiddly/unintuitive and I think we should add some developer ergonomics (a better error message at least)

**Comment by tractorcow** [comment]
@sminnee what actually happens if you try to upgrade upgrade-code upgrade vendor/symbiote-libary/silverstripe-elastica? What differs between running that path vs that path + `src`?

**Comment by maxime-rainville** [comment]
Probably related to #96. 

If we end up picking up #85, we could look at this one at the same time.

**Comment by maxime-rainville** [comment]
Some high level task to fix this:
* Update `add-namespace` so it can work on modules and create matching `.upgrade.yml` files.
* Update `upgrade` and `inspect` so it can be applied to specific folders in vendor.
* Make sure all these things work both for vendor module and project root module.
* Create a doc entry about upgrading modules
* Stretch goal: Create a recompose command that can work on a vendor's composer file.

**Comment by bergice** [comment]
This should be resolved with https://app.zenhub.com/workspaces/open-sorcerers-52b2f493f0808b12020000f8/issues/silverstripe/silverstripe-upgrader/96

**Comment by maxime-rainville** [comment]
@bergice Maybe avoid posting ZenHub links as those won't make sense for people outside of the OS team.
