### ISSUE TITLE
Debug::log not rewritten

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-upgrader#79]
Calls to `SilverStripe\Dev\Debug::log($message)` are not rewritten

Presumably these should be rewritten to `Injector::inst()->get(LoggerInterface::class)->log($messsage, 'notice')`

**Comment by maxime-rainville** [comment]
We already have an issue for this on Framework I think ... https://github.com/silverstripe/silverstripe-framework/issues/7915

**Comment by sminnee** [comment]
It wasn't specifically listed but it is now. Closing this.
