### ISSUE TITLE
Framework `.upgrade.yml` excludes vendor - makes it difficult to work on module

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-upgrader#96]
[`.upgrade.yml` in framework](https://github.com/silverstripe/silverstripe-framework/blob/31ad3cdaab9623230ce6bdad4e53f6a9a6c9baba/.upgrade.yml#L951-L953) is configured to exclude `vendor`:
```yml
excludedPaths:
  - '*fixtures*'
  - '*vendor*'
```

This is a sensible exclusion, however if you are upgrading vendor module and you are working from a test SilverStripe project, it's going to make it hard to run some commands because the upgrader will want to ignore your module.

This was reported by Dylan Wagstaff while he was trying to run this command.
```
upgrade-code upgrade vendor/bringyourownideas/silverstripe-composer-security-checker/src/
```
We need a way to _unexclude_ certain paths. It could be that if you are explicitly using a path that is excluded, we disable any exclusion that is getting in the way.

# Pull Requests
- [ ] https://github.com/silverstripe/silverstripe-upgrader/pull/139/

**Comment by NightJar** [comment]
I like that idea as a solution, most particularly as this is consistent with directing to a singular concrete file - which _does_ work, currently.

i.e.
```
upgrade-code upgrade vendor/bringyourownideas/silverstripe-composer-security-checker/src/Models/SecurityAlert.php
```
worked. But one by one upgrading is one heck of an effort, currently worked around by moving the folder to installation root, upgrading all at once via a directory path, then moving back to vendor.

**Comment by tractorcow** [comment]
I think it should still exclude vendor in sub-paths, but if you used this command.
```
upgrade-code upgrade vendor/bringyourownideas/silverstripe-composer-security-checker/src/
```

It should only exclude paths inside "src", not up to and including the whole path.

**Comment by maxime-rainville** [comment]
@tractorcow That was my thinking as well. We should probably ignore the full path when deciding whatever to exclude or not a file and use the CodeCollection path instead.

**Comment by sminnee** [comment]
I would probably do this by passing the path relative to your upgrade-code argument to the exclusion filter

So if I call upgrade-code vendor/sminnee/thing

Then vendor/sminnee/thing/section will only pass “src” to yhe exclusion filter

**Comment by maxime-rainville** [comment]
I glance at the code for Disk Collection. Shouldn't be too much of a mission to fix. Reducing the effort to easy. It's probably a 2 in terms of complexity, maybe a 1.
